sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: DNdzxI4gyCymIA+hheHB1EHkWJXHpvsarovrMj3WrqfzvtHHSMXwaQAuvh0FbVz1kXJ6yLh69ZriOk+mYRyCBMbmNZrmAQH9ig6H3IZww2prI5Y5yo4g++elM/HIL9kF4pgouWq3PWyJgDrOL5yeZn/ZEj9LqjmYTcNSXT6XJvG/6tPgH5YypMHARw5QbJb/GDT+0AkbbO9g1z1uUTa90fvcCplGuYKUjRXdfq/VKI8BnnutAMKThf1EWdHWA80YmPfiDWO0UglmYTm+pgatlHwmJUBarpdn76TeTZvjvdZ0avTapfrpctUydxbHytUApLz/0EsSV6ayg6W0KdohO6P9CBVZyScpjDe544/DMIauOiPWAQcAXUmc8nJZC/wEPGGCijjfVKsGJHN5RxFnt3WgNaFOKoKj0BzSc25afpA2//ArBE/4eZUmnskrDRkUncv26790QXtVIem8wlKZhwLGbjxQCVQoo/bNeKUgujOzm4e6UGwD8zLhJcyRkhOaJDJpRCMHXNbAR2rbXU85q5PVIr/EfRULkBYWnzcALIG0slKB3z4hVwpBwU9C4S6fpSwFtv5ZbaLTiyuq6lhESNdA3WUkjudrSnwoZR9LPCZh/8D3dT8OsgkN6Esf2ctSKakfhVpPSct6obk3iG+BVPjjPglyGpRxu8mjglKRJ44=
  - secure: HF5e2N1k6S6cKu3Q+0iRuJPIkKLXiB4c70pl4LPQEH5CgbFfL8ykK2GSZ4XvzvHX2A9QlVEmHKdMqyOCD43hXSEK6e7FZPUM9f1JOXAp1EQK+yHDQj474LCK76Z7pariXUkaYByij8qfkNMf6CHtI0lEjFo839P1tZHrTyT7ssyvpN1kZpWH1zKWJ6cqVn2rk1mXjTKe6aYqAw0Zp+oeZXp2s36ejNoce3FASUELKPoX024+CfS5sQl2FbDg7fnBfR+QMrcOB8a1NVGmkZYlPrhonGLMVDnmXsxOA3LxeGb9DF1HzyQv6H0dVrjqc6XoS9cjzuCLhzSYjnwywKpAZfPs1PE8VffC0so2DS9b5lGSSzMq3gHZTQ44tFP3wfPiX7b96fE5Vsm2ofIUCpU0j+JL+i7V4dhm1Z9BTOpWjG4nN6lRZ+tfWYXjDN3JpEmH4+ZOxL7hq4jAjQA9X8QicV/gZ3EpP+JM7fvDVGwfTFFuTIlr202FAD5zpUbAZvXqKA4owXC9ygsyG+2VZFcgqFPHZLWpWZ+BMKBQ0rmyqeEYgPE5KN4Ff1yCZTlnrGDyS13ign+3PeimKdwR0youogzV1p06tNZWLUi8Ml45krukKOLJU7YpmCOGFuRc9pVg4/sjubpNE9FrwK6of+y9Z6Xc9+1WgNmcDUYaVJgfJek=
  - secure: EZvY61IaQLIJMVlzbUC6g//f82uIL+cwrtcq8gAZV4aCyBBl4ol2VkeGLcJd03O/F2+2r+tMv5wkD5CL8TpxE8lF3JYeTHvnTdLDmx/Ov1XDqccoHL8uBoQMVg2ESpeMVaBJAS5DeUwFEGlOrHekA1TFTg8254TGIhOEIQr3ecSh39KgdaDHtVZulLeXAPMthfk7A25X0nEBksAtAYGEohmqboQ0Tc/SIlQSzZYbnxjin7BW8QLq24Mnpw32YKkhcyaMcaIMV2Xfk+PXyZnqQLuaboVa5tJPvlz7eva26GratqXd4RmGOefMXTQWRLyQFVmvYdqQ4mhbpJIcOQjcDLob/K85TJ+PCUvS4MQtzNHQaw1I5iJFyxbMFr1s4czgNFgcOf0APTIu1qii5Ztg6NtxTAhNMS+pWVqHj/C2pg5Am0aCmTT/MS2+j0zA/5G9oasuYO7zkAPIU9lDeQy4adiWVvAbjJsqjSRh+V3JPytU0PUpbOmWhs9xJ/k1h9qAtM4BVY1yiRkcQ+DLrNrLUJrjYkJbuvYwbzURrNSmVWD+eg7LAMI2rJTcellpvqhWyg7eoFC5WszCBETnPzdfkVIn3tzqAP8xFcGlPcQVM0tuQTJIBXprCzboq9HZwuvQGD97Uhq076CxKDuomAbFmaZ0n45nRKgE8kQtTGQbP5w=
  - secure: 3Hmeo2EzgQuMijaeRBH6WK578IlENli/Dtp/3Y5aMnzUuWEm83rzUPzcODOySMzbu41lLxYswVNhzRoXbO2ZVgtYgUTMXP86xLZNGbcBMUCITT8qjPd8yNr24KAWWnPK7SiMBox/ACu0hRWRjBaB3VU7neR40o9Q99F+JRcTzADoMaQmJOL7YTpzEHHyAVIP9sE3Y1b7uA8iFO9OHxbgUIr/pkk2LmgBXo81Af9ORlJz3gcbXHXP/PwnoRQOB5TtE9oUf35g8eLkkKVOWGxCqeXhOtjTKkyQ98lEciAEcJQ5kLK1S3ilxhwV8g6dZa3E36GqPQ+m7Rx3NA2V6f2Lp8x6Vu9tEY0BNC4hy9FD563ZbWknrNILXxXEmQfyp4dZrPXklkeIWTykvHnBM/KnUT3TibfHRuCW2/NS/cR/7gAkDihbv8kKuO8UBqk0DOjCMwZJxM47Qs1/GH5QCNlRlUjFSAFXoh2QEetakSC8ACbyoS8XLEYVKp4jKQ4aRStWEEPn0lOCD/ZG8Y0vwGRnBUWtgxuWRox5bkNPNt8+9My3SagOzN0+1p2Y8KRTPVrKGu6GRan6x13lhoIp9D9h2N7pqx3EzawgARwODywRU2lsXllmbsvDlPG5S7PN8rkNsh+t+Esypv/bHecnsK6do+zOEcHfHx06wGgzLwai7aw=
before_install:
- openssl aes-256-cbc -K $encrypted_32be711beb33_key -iv $encrypted_32be711beb33_iv -in .sign.asc.enc -out .sign.asc -d
- gpg2 --fast-import .sign.asc
- export GPG_TTY=$(tty)
- cp .settings.xml $HOME/.m2/settings.xml
after_success:
- mvn clean test coveralls:report
deploy:
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: mvn deploy
    skip_cleanup: true
    on:
      tags: true
notifications:
  email: false
  slack:
    rooms:
      secure: 7oxtuGlwmdxHuuglUiMAF/oH27IdvbIRVzGcdrxdFh50cmP2foH8jKrarBC2y0oDc7to4YmW6gT3mBEcbRjED767IIIDXIr30we5l8vNmTKyV7fDgL0VxjukUYuWn3cjSkkjbrwY9bjWSlyyXmdDhADmxue9SYO84ryjxLoGaaIKLPt7gyAz/x+AahNfaLZcKDRDOy13iaWczi8X5spjGg7seT1zqwf4l3aiKegfrH0UCYyitxIGd8clPwzmyW5656RND0STuC72Miqn3S52PVlS1uesni4wV5YC6BYiiLf7VeHCCqp8eX0CGigKPDbg9PrXUVOMVlDIdCHWxRem9ntT9FSFoK+r1+rv893lH2mkyFur3XO+Nu0zhc1SGBg7t+K6ugmxvEp2iImlx2qoaqJYc94QIScMe5GkQQlNvuno9Sa8AqCy5evzf0MjSGbkHUBZJYzN0DDZlH+aFOq3Wu1nreUGbMwAUwv8OMKOiLeuYhUxVYgZEEh3DjdtPvbhcClbgpkA0sLTYs9AK0fro9EKVgqLLCVH8STgdGDrxskEM8XHKdN9b+HcPLkcqXRNXycdMTa7sRc1TJOnb7weO4dqpHRsbiCcNx9zVGQr3sG9Nr8WF75HfrtFPkdU5OkOfPGP+pNd1qX9HglosZS5RZLB7Iq3bUYNKQyoC0P/P18=
    on_success: change
    on_failure: always
