version: 2.1

executors:
  maven:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: /tmp/build

jobs:
  build:
    executor: maven
    steps:
      - checkout
      - restore_cache:
          key: crowd-timestamp-to-date-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      - run:
          name: Compile and Package
          command: mvn package -DskipTests
      - run:
          name: Copy Artifacts into separate Directory
          command: mkdir -p /tmp/artifacts && cp target/*.{jar,obr} /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/build
          paths:
            - .
      - save_cache:
          paths:
            - ~/.m2
          key: crowd-timestamp-to-date-plugin-{{ checksum "pom.xml" }}
  deploy:
    executor: maven
    steps:
      - attach_workspace:
          at: /tmp/build
      - restore_cache:
          key: crowd-timestamp-to-date-plugin-{{ checksum "pom.xml" }}
      - run:
          name: Decrypt Signing Key
          command: openssl aes-256-cbc -S ${SIGN_ASC_SALT} -K ${SIGN_ASC_KEY} -iv ${SIGN_ASC_IV} -in .circleci/sign.asc.enc -out .circleci/sign.asc -d
      - run:
          name: Import Signing Key
          command: gpg --no-tty --batch --import .circleci/sign.asc
      - run:
          name: Deploy to Maven Central
          command: mvn deploy -DskipTests -s .circleci/settings.xml
      - save_cache:
          paths:
            - ~/.m2
          key: crowd-timestamp-to-date-plugin-{{ checksum "pom.xml" }}

workflows:
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
          context: deploy-maven
